#pragma once
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <limits>
#include <iomanip>
#include <cmath>
#include <functional>
#include <algorithm>
#include <numeric>
#include <ctime>
#include <limits>
#include <ios>
#include <cstdlib>
#include <chrono>
#include <random>
#include <sstream>

using std::cin;
using std::cout;
using std::endl;
using std::string;
using std::vector;
using std::setw;
using std::left;
using std::right;
using std::fixed;
using std::setprecision;
using std::numeric_limits;
using std::streamsize;
using std::sort;
using std::stoi;
using std::move;
using std::ostringstream;
using std::istringstream;
using std::ifstream;
using std::ofstream;
using std::cerr;
using std::to_string;
